version: "3.9"
services:
    auth:
        build: ./auth
        hostname: auth
    db:
        image: postgres:13
        hostname: db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
    backend:
        build: ./backend
        hostname: backend
#        depends_on:
#            - auth
#            - db
        ports:
            -   "8080"
        environment:
            AUTH_HOST: auth
            AUTH_SERVICE_URL: http://auth:6969
            DB_HOST: db
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_NAME: postgres

    loadbalancer:
        image: nginx:latest
        hostname: loadbalancer
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            -   backend
        ports:
            -   "42069:42069"

networks:
    default:
        name: backend
        driver: bridge
