// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/courselab/pollex/pollex-backend/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// Locations is an autogenerated mock type for the Locations type
type Locations struct {
	mock.Mock
}

// GetLocations provides a mock function with given fields:
func (_m *Locations) GetLocations() []domain.Location {
	ret := _m.Called()

	var r0 []domain.Location
	if rf, ok := ret.Get(0).(func() []domain.Location); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Location)
		}
	}

	return r0
}

type mockConstructorTestingTNewLocations interface {
	mock.TestingT
	Cleanup(func())
}

// NewLocations creates a new instance of Locations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLocations(t mockConstructorTestingTNewLocations) *Locations {
	mock := &Locations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
